### ISSUE TITLE
Error running yo cucumber

### ISSUE THREAD

**Issue by rcbop** [lukasz-kaniowski/generator-cucumber#6]
When I try to run `yo cucumber`. Right after installing it using `sudo npm -g install generator-cucumber`

I get this error.

    readline.js:925
              throw err;
              ^

    TypeError: Cannot assign to read only property 'name' of function (args, options) {

      this.directory('.', 'features');
    }
        at Object.<anonymous> (/usr/local/lib/node_modules/generator-cucumber/app/index.js:9:16)
        at Module._compile (module.js:413:34)
        at Object.Module._extensions..js (module.js:422:10)
        at Module.load (module.js:357:32)
        at Function.Module._load (module.js:314:12)
        at Module.require (module.js:367:17)
        at require (internal/module.js:16:19)
        at Object.defineProperty.get [as cucumber:app]     (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/lib/store.js:40:23)
        at Store.get (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/lib/store.js:64:35)
        at Environment.get (/usr/local/lib/node_modules/yo/node_modules/yeoman-     environment/lib/environment.js:259:21)

**Comment by lukasz-kaniowski** [comment]
Thanks for reporting this. Will have to update this generator to new api.

**Comment by lukasz-kaniowski** [comment]
this is now fixed. @rcbop can you confirm that new version is working for you?

**Comment by rcbop** [comment]
Awesome. I confirm it's fixed. Thanks!
